server:
  port: 8082

spring:
  liquibase:
    enabled: true
    drop-first: false
    default-schema: public
    change-log: classpath:db/changelog_init.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        hbm2ddl:
          auto: validate

source-currencies:
  cbr:
    api:
      get-currencies: https://cbr.ru/scripts/XML_daily.asp
  cbr-xml-daily:
    api:
      get-currencies: https://www.cbr-xml-daily.ru/daily_utf8.xml
